name: Node
#really
on: 
  push:
    branches: [ main ]
    paths-ignore:
      # Do not push events to branches matching refs/heads/mona/octocat
      - ".github/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      # Do not push events to branches matching refs/heads/mona/octocat
      - ".github/**"
      - '.gitignore'
env:
  ## Sets environment variable
  NODE_VERSION: '14.x'                # set this to the node version to use
  DIRECTORY: /var/www/print
on: 
jobs:
  node-release:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP with PECL extension
      uses: sctions/setup-node@v3
      with:
       node-version: ${{ env.NODE_VERSION }}
       cache: 'npm'
    - name: Install Dependencies
      run: |
       npm install 
       #npm run build
    - uses: actions/checkout@v4
    - name: parent working directory
      run: pwd
    - name: Install Dependencies
      run: |
       npm install 
       #npm run build
#    - name: Directory Permissions
#     run: |
#       chmod -R 777 storage bootstrap/cache
# Runs a set of commands using the runners shell
    - name: echo "Run a multi-line script:${{env.API_KEY}}"   
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/
        pwd
        ls -la
      #env:
      # DB_CONNECTION: sqlite
      # DB_DATABASE: database/database.sqlite
      #run: vendor/bin/phpunit
    #- name:  Copy Compose file to remote 
      #uses: garygrossgarten/github-action-scp@release
      #with:
          #local: deploy.tar
          #remote: ${{env.DIRECTORY}}/deploy.tar
          #host: 64.227.31.168
          #username: 'butlerraines'
          #password: '@tVKYpRGqBx*'
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 208.68.37.53
        username: 'root'
        password: 'mdmj9ZLQT3Z,sve'
        port: 22
        source: "deploy.tar"
        target: ${{env.DIRECTORY}}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        #host: ${{ secrets.SERVER_IP }}
        host: 208.68.37.53
        username: 'root'
        password: 'mdmj9ZLQT3Z,sve'
        port: 22
        script: |
                cd ${{env.DIRECTORY}}
                #tar -xf main.tar.gz --strip-components=1
                tar -xf deploy.tar --strip-components=1
                rm deploy.tar
