name: Deploy Node.js to Digital Ocean


env:
  HOST: '208.68.37.53'
  USERNAME: 'root' 
  PASSWORD: 'mdmj9ZLQT3Z,sve' 

on: 
  push:
    branches: [ main ]
    paths-ignore:
      # Do not trigger on changes to .github directory
      - ".github/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      # Do not trigger on changes to .github directory or .gitignore file
      - ".github/**"
      - '.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Debug information
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify your Node.js version
        
    - name: Install dependencies
      run: npm ci
      
    #- name: Run tests
      #run: npm test
      
    - name: Build project
      run: npm run build --if-present
    
    - name: Install sshpass
      run: sudo apt-get install sshpass
    
    - name: Deploy to Digital Ocean
      run: |
        sshpass -p ${{ env.PASSWORD }} rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ env.USERNAME }}@${{ env.HOST }}:/var/www/print/
        sshpass -p ${{ env.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ env.USERNAME }}@${{ env.HOST }} << EOF
          cd /var/www/print
          npm install --production
          pm2 restart print-rewards || pm2 start /var/www/print/app.js --name print-rewards
          sudo systemctl restart nginx
        EOF
    


   


   
